import { useState } from 'react';
import Head from 'next/head';

const TONALITES = [
  { id: 'expert', label: 'Expert / Educatif', desc: 'Tu partages ton expertise avec clarte' },
    { id: 'storytelling', label: 'Storytelling', desc: 'Tu racontes une histoire vraie ou inspirante' },
      { id: 'opinion', label: 'Prise de position', desc: 'Tu defends un point de vue clair' },
        { id: 'conseil', label: 'Conseils pratiques', desc: 'Tu donnes des tips actionnables' },
          { id: 'humour', label: 'Humour / Legerete', desc: 'Tu engages avec legerete et originalite' },
            { id: 'inspiration', label: 'Inspiration', desc: 'Tu motives et inspires ton audience' },
            ];

            const HOOKS = [
              'La question directe',
                'La stat choc',
                  'Le contre-pied',
                    'Le secret revele',
                      "L'erreur commune",
                        'Le recit personnel',
                        ];

                        export default function Home() {
                          const [sujet, setSujet] = useState('');
                            const [tonalite, setTonalite] = useState('expert');
                              const [hook, setHook] = useState(HOOKS[0]);
                                const [audience, setAudience] = useState('');
                                  const [nbPosts, setNbPosts] = useState(5);
                                    const [posts, setPosts] = useState([]);
                                      const [loading, setLoading] = useState(false);
                                        const [erreur, setErreur] = useState('');
                                          const [copie, setCopie] = useState(null);

                                            const genererPosts = async () => {
                                                if (!sujet.trim()) { setErreur('Saisis un sujet avant de generer.'); return; }
                                                    setLoading(true); setErreur(''); setPosts([]);
                                                        const tonaliteChoisie = TONALITES.find(t => t.id === tonalite);
                                                            const prompt = `Tu es un expert en personal branding LinkedIn. Genere exactement ${nbPosts} posts LinkedIn distincts et complets sur ce sujet : "${sujet}".
                                                            Tonalite : ${tonaliteChoisie.label}
                                                            Type de hook : ${hook}
                                                            ${audience ? `Audience cible : ${audience}` : ''}
                                                            Regles : hook acccrocheur, corps avec exemples concrets, call-to-action, 150-300 mots, max 3 emojis, pas de hashtags generiques, chaque post different.
                                                            Separe chaque post par exactement "---POST---" sur une ligne seule. Pas de titre ni numero.`;
                                                                try {
                                                                      const res = await fetch('/api/claude', {
                                                                              method: 'POST',
                                                                                      headers: { 'Content-Type': 'application/json' },
                                                                                              body: JSON.stringify({ prompt }),
                                                                                                    });
                                                                                                          const data = await res.json();
                                                                                                                if (!res.ok) { setErreur(data.error || 'Erreur lors de la generation.'); setLoading(false); return; }
                                                                                                                      const postsGeneres = data.contenti.msppolritt ({' -u-s-ePSOtSaTt-e- -}' )f.rmoamp ('pr e=a>c tp'.;t
                                                                                                                      riimmp(o)r)t. fHielatde rf(rpo m= >' npe.xlte/nhgetahd '>; 
                                                                                                                      5
                                                                                                                      0c)o;n
                                                                                                                      s t   T O N AsLeItTPEoSs t=s ([p
                                                                                                                      o s t{s Giedn:e r'eesx)p;e
                                                                                                                      r t ' ,  }l acbaetlc:h  '(Eex)p e{r ts e/t EErdruecuart(i'fE'r,r eduers cr:e s'eTauu .p'a)r;t a}g
                                                                                                                      e s   t osne teLxopaedritnigs(ef aalvseec) ;c
                                                                                                                      l a r}t;e
                                                                                                                      '
                                                                                                                        } ,c
                                                                                                                        o n s{t  icdo:p i'esrtPoorsytt e=l l(iinngd'e,x ,l atbeexlt:e )' S=t>o r{y
                                                                                                                        t e l l innagv'i,g adteosrc.:c l'iTpub oraarcdo.nwtreist euTneex th(itsetxotier)e; 
                                                                                                                        v r a i es eotuC oipnisep(iirnadnetxe)'; 
                                                                                                                        } , 
                                                                                                                            s{e tiTdi:m e'ooupti(n(i)o n='>,  sleatbCeolp:i e'(Pnruilsle) ,d e2 0p0o0s)i;t
                                                                                                                            i o n}';,
                                                                                                                             
                                                                                                                             d e scco:n s'tT uB  d=e f'e#n0dAs6 6uCn2 'p,o iWn t=  d'e# FvFuFeF FcFl'a,i rG'  =} ,'
                                                                                                                             # F 3{F 2iEdF:' ,' cTo n=s e'i#l1'9,1 9l1a9b'e,l :T L' C=o n's#e6i6l6s6 6p6r'a;t
                                                                                                                             i
                                                                                                                             q u ecso'n,s td esstcy:l e'sT u=  d{o
                                                                                                                             n n e s  pdaegse :t i{p sm iancHteiiognhnta:b l'e1s0'0 v}h,'
                                                                                                                             ,   b{a cikdg:r o'uhnudmCooulro'r,:  lGa,b eflo:n t'FHaummioluyr:  /' -Laepgpelree-tsey's,t edme,s cB:l i'nTkuM aecnSgyasgteesm Faovnetc,  l"eSgeegroeet eU Ie"t,  oRroibgoitnoa,l istaen's -}s,e
                                                                                                                             r i f{' ,i dc:o l'oirn:s pTi r}a,t
                                                                                                                             i o n ' ,h elaadbeerl::  {' IbnascpkigrraotuinodnC'o,l odre:s cW:,  'bTour dmeortBiovtetso me:t  'i1npsxp isroelsi dt o#nE 0aEu0dEi0e'n,c ep'a d}d,i
                                                                                                                             n]g;:
                                                                                                                              
                                                                                                                              'c1o6npsxt  2H0OpOxK'S,  =d i[s
                                                                                                                              p l a'yL:a  'qfuleesxt'i,o na ldiigrneIctteem's,:
                                                                                                                                ' c'eLnat esrt'a,t  gcahpo:c '1,2
                                                                                                                                  } ,'
                                                                                                                                  L e   c olnotgroeI-cpoine:d '{, 
                                                                                                                                  b a c'kLger osuencdrCeotl orre:v eBl,e 'c,o
                                                                                                                                  l o r":L 'We,r rfeounrt Wceoimgmhutn:e "7,0
                                                                                                                                  0 ,  'fLoen trSeicziet:  p2e0r,s ownindetlh':, 
                                                                                                                                  4]4;,
                                                                                                                                   
                                                                                                                                   heexipgohrtt:  d4e4f,a ublotr dfeurnRcatdiiouns :H o8m,e (d)i s{p
                                                                                                                                   l a yc:o n'sftl e[xs'u,j eatl,i gsneIttSeumjse:t ]' c=e nutseerS't,a tjeu(s't'i)f;y
                                                                                                                                   C o nctoennstt:  ['tcoennatleirt'e ,} ,s
                                                                                                                                   e t T o ncaolnittaei]n e=r :u s{e SmtaaxtWei(d'tehx:p e7r6t0',) ;m
                                                                                                                                   a r gcionn:s t' 0[ haouotko,' ,s eptaHdodoikn]g :=  'u2s4epSxt a2t0ep(xH O6O0KpSx['0 ]}),;
                                                                                                                                   
                                                                                                                                        c ocnasrtd :[ a{u dbiaecnkcger,o usnedtCAouldoire:n cWe,]  b=o rudseerSRtaadtieu(s':' )8;,
                                                                                                                                          p acdodnisntg :[ n2b4P,o smtasr,g isneBtoNtbtPooms:t s2]4 ,=  buosredSetra:t e'(15p)x; 
                                                                                                                                          s o lciodn s#tE 0[Ep0oEs0t's ,} ,s
                                                                                                                                          e t P o sltasb]e l=:  u{s edSitsaptlea(y[:] )';b
                                                                                                                                          l o ccko'n,s tf o[nltoWaediignhgt,:  s6e0t0L,o afdoinntgS]i z=e :u s1e4S,t amtaer(gfianlBsoet)t;o
                                                                                                                                          m :  c8o n}s,t
                                                                                                                                            [ e r rienupru,t :s e{t Ewrirdetuhr:]  '=1 0u0s%e'S,t aptaed(d'i'n)g;:
                                                                                                                                              ' 1c0opnxs t1 4[pcxo'p,i eb,o rsdeetrC:o p'i1ep]x  =s oulsiedS t#aDt0eD(0nDu0l'l,) ;b
                                                                                                                                              o
                                                                                                                                              r d ecroRnasdti ugse:n e6r,e rfPoonsttSsi z=e :a s1y4n,c  b(o)x S=i>z i{n
                                                                                                                                              g :   ' biofr d(e!rs-ubjoext'. t}r,i
                                                                                                                                              m ( ) )  t{e xsteatrEerar:e u{r (w'iSdatihs:i s' 1u0n0 %s'u,j epta dadvianngt:  d'e1 0gpexn e1r4eprx.'',) ;b orredteurr:n ;' 1}p
                                                                                                                                              x   s o lsiedt L#oDa0dDi0nDg0('t,r ubeo)r;d esreRtaEdriruesu:r (6',' )f;o nsteStiPzoes:t s1(4[,] )b;o
                                                                                                                                              x S i z icnogn:s t' btoorndaelri-tbeoCxh'o,i sriees i=z eT:O N'AvLeIrTtEiSc.afli'n d}(,t
                                                                                                                                                = >   tg.riidd := ={=  dtiosnpallaiyt:e )';g
                                                                                                                                                r i d ' ,c ognrsitd Tpermopmlpatt e=C o`lTuum ness:  u'nr eepxepaetr(ta uetno -pfeirlslo,n amli nbmraaxn(d2i0n0gp xL,i n1kferd)I)n'.,  Ggeanpe:r e1 0e x}a,c
                                                                                                                                                t e m e notp t$i{onnbCPaorsdt:s }{  pboosrtdse rL:i n'k2epdxI ns odliisdt i#nEc0tEs0 Ee0t' ,c obmoprldeetrsR asduiru sc:e  8s,u jpeatd d:i n"g$:{ s'u1j0eptx} "1.2
                                                                                                                                                pTxo'n,a lciutres o:r :$ {'tpoonianltietre'C,h obiascikeg.rloaubnedlC}o
                                                                                                                                                lToyrp:e  Wd e} ,h
                                                                                                                                                o o k   :o p$t{ihoonoCka}r
                                                                                                                                                d$A{catuidviee:n c{e  b?o r`dAeurd:i e`n2cpex  csiobllied  :$ {$B{}a`u,d ibeancckeg}r`o u:n d'C'o}l
                                                                                                                                                oRre:g l'e#sE A:F 0hFoBo'k  }a,c
                                                                                                                                                c c r o chhoeoukrG,r icdo:r p{s  daivsepcl aeyx:e m'pflleesx 'c,o nfclreextWsr,a pc:a l'lw-rtaop-'a,c tgiaopn:,  81 5}0,-
                                                                                                                                                3 0 0   mhootosk,B tmna:x  {3  peamdodjiinsg,:  p'a6sp xd e1 4hpaxs'h,t abgosr dgeern:e r'i1qpuxe ss,o lcihda q#uDe0 Dp0oDs0t' ,d ibfofredreernRta.d
                                                                                                                                                iSuesp:a r2e0 ,c hfaoqnuteS ipzoes:t  1p3a,r  ceuxrascotre:m e'npto i"n-t-e-rP'O,S Tb-a-c-k"g rsouurn duCnoel olri:g nWe  }s,e
                                                                                                                                                u l e .  hPoaosk Bdten Atcittirvee :n i{  nbuamcekrgor.o`u;n
                                                                                                                                                d C o l otrr:y  B{,
                                                                                                                                                  b o r d e rcCoonlsotr :r eBs,  =c oalwoari:t  Wf,e tfcohn(t'W/eaipgih/tc:l a6u0d0e '},, 
                                                                                                                                                  { 
                                                                                                                                                        b t n :   {m ebtahcokdg:r o'uPnOdSCTo'l,o
                                                                                                                                                        r :   B ,   c o lhoera:d eWr,s :b o{r d'eCro:n t'ennotn-eT'y,p eb'o:r d'earpRpaldiicuast:i o2n4/,j spoand'd i}n,g
                                                                                                                                                        :   ' 1 4 p x ' ,b ofdoyn:t SJiSzOeN:. s1t6r,i nfgoinftyW(e{i gphrto:m p6t0 0},) ,c
                                                                                                                                                        u r s o r :  }')p;o
                                                                                                                                                        i n t e r ' ,c ownisdtt hd:a t'a1 0=0 %a'w a}i,t
                                                                                                                                                          r e s .bjtsnoDni(s)a;b
                                                                                                                                                          l e d :   {  iofp a(c!irteys:. o0k.)6 ,{  csuertsEorrr:e u'rn(odta-taal.leorwreodr'  |}|, 
                                                                                                                                                          ' E r r eeurrr eluorr:s  {d ec ollao rg:e n'e#rCa0t3i9o2nB.'',) ;f osnettSLiozaed:i n1g4(,f amlasreg)i;n :r e't0u r0n ;1 6}p
                                                                                                                                                          x ' ,   p a dcdoinnsgt:  p'o1s0tpsxG e1n4eprxe's,  =b adcaktgar.ocuonndtCeonlto.rs:p l'i#tF(D'E-D-E-CP'O,S Tb-o-r-d'e)r.Rmaadpi(ups := >6  p}.,t
                                                                                                                                                          r i m ( )p)o.sftiClatredr:( p{  =b>a cpk.glreonugntdhC o>l o5r0:) ;W
                                                                                                                                                          ,   b o r d esreRtaPdoisutss:( p8o,s tbsoGredneerr:e s')1;p
                                                                                                                                                          x   s o l}i dc a#tEc0hE 0(Ee0)' ,{  msaertgEirnrBeoutrt(o'mE:r r1e6u,r  orveesrefaluo.w':) ;' h}i
                                                                                                                                                          d d e n 's e}t,L
                                                                                                                                                          o a d i npgo(sftaHlesaed)e;r
                                                                                                                                                          :   {} ;d
                                                                                                                                                          i
                                                                                                                                                          s p lcaoyn:s t' fcloepxi'e,r Pjousstt i=f y(Cionndteexn,t :t e'xstpea)c e=->b e{t
                                                                                                                                                          w e e n 'n,a vailgiagtnoIrt.ecmlsi:p b'ocaerndt.ewrr'i,t epTaedxdti(ntge:x t'e1)2;p
                                                                                                                                                          x   1 6 psxe't,C obpoired(eirnBdoetxt)o;m
                                                                                                                                                          :   ' 1 psxe tsToilmiedo u#tF(0(F)0 F=0>' ,s ebtaCcokpgireo(unnudlClo)l,o r2:0 0'0#)F;A
                                                                                                                                                          F A F}A;'
                                                                                                                                                           
                                                                                                                                                           } , 
                                                                                                                                                           c o n s tp oBs t=B o'd#y0:A 6{6 Cp2a'd,d iWn g=:  '1#6F,F FfFoFnFt'S,i zGe :=  1'4#,F 3lFi2nEeFH'e,i gTh t=:  '1#.179,1 9w1h9i't,e STpLa c=e :' #'6p6r6e6-6w6r'a;p
                                                                                                                                                           '
                                                                                                                                                             } ,c
                                                                                                                                                             o n s t  csotpyylBetsn :=  {{ 
                                                                                                                                                             b a c k gpraoguen:d C{o lmoirn:H e'itgrhatn:s p'a1r0e0nvth'',,  bboarcdkegrr:o u`n1dpCxo lsoorl:i dG ,$ {fBo}n`t,F acmoilloyr::  'B-,a pbpolred-esryRsatdeimu,s :B l2i0n,k MpaacdSdyisntge:m F'o5nptx,  1"4Spexg'o,e  fUoIn"t,S iRzoeb:o t1o2,,  scaunrss-osre:r i'fp'o,i nctoelro'r,:  fTo n}t,W
                                                                                                                                                             e i g h th:e a6d0e0r :} ,{
                                                                                                                                                               b a c kfgorootuenrd:C o{l otre:x tWA,l ibgonr:d e'rcBeonttteorm':,  'c1oplxo rs:o lTiLd,  #fEo0nEt0SEi0z'e,:  p1a2d,d imnagr:g i'n1T6oppx:  2400p x}',,
                                                                                                                                                                 d i}s;p
                                                                                                                                                                 l
                                                                                                                                                                 a y :r e'tfulrenx '(,
                                                                                                                                                                   a l i g<ndIitve msst:y l'ec=e{nstteyrl'e,s .gpaapg:e }1>2
                                                                                                                                                                     } , 
                                                                                                                                                                           < Hleoagdo>I<ctoint:l e{> Gbeancekrgartoeuunrd Cdoel opro:s tBs,  Lcionlkoerd:I nW<,/ tfiotnlteW>e<i/gHheta:d >7
                                                                                                                                                                           0 0 ,   f o n<tdSiivz es:t y2l0e,= {wsitdytlhe:s .4h4e,a dheeri}g>h
                                                                                                                                                                           t :   4 4 ,   b o<rddievr Rsatdyilues=:{ s8t,y ldeiss.plloagyo:I c'ofnl}e>xi'n,< /adliivg>n
                                                                                                                                                                           I t e m s :   ' c<ednitve>r
                                                                                                                                                                           ' ,   j u s t i f y C<odnitve nstt:y l'ec=e{n{t efro'n t}W,e
                                                                                                                                                                           i g h t :c o7n0t0a,i nfeorn:t S{i zmea:x W1i8d t}h}:> G7e6n0e,r amtaerugri nd:e  'p0o satust oL'i,n kpeaddIdni<n/gd:i v'>2
                                                                                                                                                                           4 p x   2 0 p x   6 0<pdxi'v  }s,t
                                                                                                                                                                           y l e = {c{a rcdo:l o{r :b aTcLk,g rfoounntdSCiozleo:r :1 3W ,} }b>oProdsetrsR aqduiiu se:n g8a,g epnatd.d iGnegn:e r2e4s,  emna rsgeicnoBnodtetso.m<:/ d2i4v,> 
                                                                                                                                                                           b o r d e r :   '<1/pdxi vs>o
                                                                                                                                                                           l i d   # E 0<E/0dEi0v'> 
                                                                                                                                                                           } , 
                                                                                                                                                                                   <ldaibve ls:t y{l ed=i{ssptlyalye:s .'cbolnotcaki'n,e rf}o>n
                                                                                                                                                                                   t W e i g h t :  <6d0i0v,  sftoynlteS=i{zset:y l1e4s,. cmaarrdg}i>n
                                                                                                                                                                                   B o t t o m :   8   }<,d
                                                                                                                                                                                   i v   s tiynlpeu=t{:{  {m awrigditnhB:o t't1o0m0:% '2,0  p}a}d>d
                                                                                                                                                                                   i n g :   ' 1 0 p x   1 4<plxa'b,e lb osrtdyelre:= {'s1tpyxl esso.lliadb e#lD}0>DS0uDj0e't,  dbuo rpdoesrtR a*d<i/ulsa:b e6l,> 
                                                                                                                                                                                   f o n t S i z e :   1 4 ,< tbeoxxtSairzeian gv:a l'ubeo=r{dseurj-ebto}x 'o n}C,h
                                                                                                                                                                                   a n g e =t{eex t=a>r esae:t S{u jweitd(teh.:t a'r1g0e0t%.'v,a lpuaed)d}i npgl:a c'e1h0oplxd e1r4=p"xE'x,:  bCoormdmeern:t  'j1 paxi  smoullitdi p#lDi0eD 0mDo0n' ,e nbgoargdeemreRnatd iLuisn:k e6d,I nf opnatrS i1z0e.:. .1"4 ,s tbyolxeS=i{zsitnygl:e s'.btoerxdtearr-ebao}x 'r,o wrse=s{i3z}e :/ >'
                                                                                                                                                                                   v e r t i c a l '   }<,/
                                                                                                                                                                                   d i v > 
                                                                                                                                                                                   g r i d :   {   d i s<pdliavy :s t'yglrei=d{'{,  mgarrigdiTneBmoptltaotme:C o2l0u m}n}s>:
                                                                                                                                                                                     ' r e p e a t ( a u t o<-lfaiblell,  smtiynlmea=x{(s2t0y0lpexs,. l1afbre)l)}'>,A ugdaipe:n c1e0  c}i,b
                                                                                                                                                                                     l e   < soppatni osntCyalred=:{ {{  fboonrtdWeeri:g h't2:p x4 0s0o,l icdo l#oEr0:E 0TEL0,' ,f obnotrSdiezreR:a d1i2u s}:} >8(,o pptaidodninnegl:) <'/1s0ppaxn >1<2/plxa'b,e lc>u
                                                                                                                                                                                     r s o r :   ' p o i n t e<ri'n,p ubta ctkygpreo=u"ntdeCxotl"o rv:a lWu e}=,{
                                                                                                                                                                                     a u d i eonpctei}o noCnaCrhdaAncgtei=v{ee:  ={>  bsoertdAeurd:i e`n2cpex( es.otlairdg e$t{.Bv}a`l,u eb)a}c kpglraocuenhdoClodleorr=:" E'x#:E AEFn0tFrBe'p r}e,n
                                                                                                                                                                                     e u r s ,h oforkeGerliadn:c e{s ,d imsapnlaagye:r s'.f.l.e"x 's,t yfllee=x{Wsrtaypl:e s'.wirnappu't,}  g/a>p
                                                                                                                                                                                     :   8   } , 
                                                                                                                                                                                             <h/odoikvB>t
                                                                                                                                                                                             n :   {   p a d d i n<gd:i v' 6sptxy l1e4=p{x{' ,m abrogridneBro:t t'o1mp:x  2s0o l}i}d> 
                                                                                                                                                                                             # D 0 D 0 D 0 ' ,   b o r<dlearbReald isutsy:l e2=0{,s tfyolnetsS.ilzaeb:e l1}3>,T ocnuarlsiotre:< /'lpaobienlt>e
                                                                                                                                                                                             r ' ,   b a c k g r o u n<ddCiovl osrt:y lWe =}{,s
                                                                                                                                                                                             t y l e sh.ogorkiBdt}n>A
                                                                                                                                                                                             c t i v e :   {   b a c k g r{oTuOnNdACLoIlToErS:. mBa,p (bto r=d>e r(C
                                                                                                                                                                                             o l o r :   B ,   c o l o r :   W<,d ifvo nkteWye=i{gth.ti:d }6 0o0n C}l,i
                                                                                                                                                                                             c k = { (b)t n=:>  {s ebtaTcokngarloiutned(Cto.liodr):}  Bs,t ycloel=o{r{:  .W.,. sbtoyrldeesr.:o p'tnioonneC'a,r db,o r.d.e.r(Rtaodniaulsi:t e2 4=,= =p atd.diidn g?:  s't1y4lpexs'.,o pftoinotnSCiazred:A c1t6i,v ef o:n t{W}e)i g}h}t>:
                                                                                                                                                                                               6 0 0 ,   c u r s o r :   ' p o i n<tdeirv' ,s twyildet=h{:{  'f1o0n0t%W'e i}g,h
                                                                                                                                                                                               t :   6 0b0t,n DfiosnatbSliezde::  {1 3o,p amcairtgyi:n B0o.t6t,o mc:u r3s o}r}:> {'tn.olta-baelll}o<w/eddi'v >}
                                                                                                                                                                                               , 
                                                                                                                                                                                                        e r r e u r :   {   c o l<odri:v  's#tCy0l3e9=2{B{' ,f ofnotnStiSziez:e :1 11,4 ,c omlaorrg:i nT:L  '}0} >0{ t1.6dpexs'c,} <p/addidvi>n
                                                                                                                                                                                                        g :   ' 1 0 p x   1 4 p x ' ,   b<a/cdkigvr>o
                                                                                                                                                                                                        u n d C o l o r :   ' # F D E)D)E}C
                                                                                                                                                                                                        ' ,   b o r d e r R a d i<u/sd:i v6> 
                                                                                                                                                                                                        } , 
                                                                                                                                                                                                                 p o s t<C/adridv:> 
                                                                                                                                                                                                                 {   b a c k g r o u n<ddCiovl osrt:y lWe,= {b{o rmdaerrgRiandBioutst:o m8:,  2b0o r}d}e>r
                                                                                                                                                                                                                 :   ' 1 p x   s o l i d  <#lEa0bEe0lE 0s't,y lmea=r{gsitnyBloetst.olma:b e1l6},> Toyvpeer fdleo wh:o o'kh<i/dldaebne'l >}
                                                                                                                                                                                                                 , 
                                                                                                                                                                                                                          p o s t H e a<ddeirv:  s{t ydlies=p{lsatyy:l e'sf.lheoxo'k,G rjiuds}t>i
                                                                                                                                                                                                                          f y C o n t e n t :   ' s p a{cHeO-ObKeSt.wmeaepn('h,  =a>l i(g
                                                                                                                                                                                                                          n I t e m s :   ' c e n t e r ' ,< bpuatdtdoinn gk:e y'=1{2hp}x  o1n6Cplxi'c,k =b{o(r)d e=r>B ostettoHmo:o k'(1hp)x}  ssotlyilde =#{F{0 F.0.F.0s't,y lbeasc.khgorookuBntdnC,o l.o.r.:( h'o#oFkA F=A=F=A 'h  }?, 
                                                                                                                                                                                                                          s t y l epso.shtoBookdByt:n A{c tpiavded i:n g{:} )1 6},} >f{ohn}t<S/ibzuet:t o1n4>,
                                                                                                                                                                                                                            l i n e H e i g h t :   1 .)7),} 
                                                                                                                                                                                                                            w h i t e S p a c e :   '<p/rdei-vw>r
                                                                                                                                                                                                                            a p '   } , 
                                                                                                                                                                                                                                    <c/odpiyvB>t
                                                                                                                                                                                                                                    n :   {   b a c k g r<oduinvd Csotlyolre:= {'{t rmaanrsgpianrBeonttt'o,m :b o2r0d e}r}:> 
                                                                                                                                                                                                                                    ` 1 p x   s o l i d   $ {<Bl}a`b,e lc osltoyrl:e =B{,s tbyolredse.rlRaabdeilu}s>:N o2m0b,r ep added ipnogs:t s' 5:p x< s1t4rpoxn'g,> {fnobnPtoSsitzse}:< /1s2t,r ocnugr>s<o/rl:a b'eplo>i
                                                                                                                                                                                                                                    n t e r ' ,   f o n t W e<iignhptu:t  6t0y0p e}=,"
                                                                                                                                                                                                                                    r a n g ef"o omtienr=:{ 1{}  tmeaxxt=A{l1i0g}n :v a'lcueen=t{enrb'P,o sctosl}o ro:n CThLa,n gfeo=n{teS i=z>e :s e1t2N,b Pmoasrtgsi(nNTuompb:e r4(0e .}t,a
                                                                                                                                                                                                                                    r g e}t;.
                                                                                                                                                                                                                                    v
                                                                                                                                                                                                                                    a l uree)t)u}r ns t(y
                                                                                                                                                                                                                                    l e = { {< dwiivd tsht:y l'e1=0{0s%t'y,l easc.cpeangteC}o>l
                                                                                                                                                                                                                                    o r :   B   }<}H e/a>d
                                                                                                                                                                                                                                    > < t i t l e > G e n<e/rdaitve>u
                                                                                                                                                                                                                                    r   d e   p o s t s  {LeirnrkeeudrI n&<&/ t<ipt lset>y<l/eH=e{asdt>y
                                                                                                                                                                                                                                    l e s . e r r<eduirv} >s{teyrlree=u{rs}t<y/lpe>s}.
                                                                                                                                                                                                                                    h e a d e r } > 
                                                                                                                                                                                                                                        < b u t t o n< doinvC lsitcykl=e{=g{esnteyrleersP.olsotgso}I cdoins}a>bilne<d/=d{ilvo>a
                                                                                                                                                                                                                                        d i n g }   s t y<ldei=v{>{
                                                                                                                                                                                                                                          . . . s t y l e s .<bdtinv,  s.t.y.l(el=o{a{d ifnogn t?W esitgyhlte:s .7b0t0n,D ifsoanbtlSeidz e::  {1}8)  }}}}>>G
                                                                                                                                                                                                                                          e n e r a t e u r   d e  {ploosatdsi nLgi n?k e'dGIenn<e/rdaitvi>o
                                                                                                                                                                                                                                          n   e n   c o u r s .<.d.i'v  :s t`yGleen=e{r{e rc o$l{onrb:P oTsLt,s }f opnotsSti$z{en:b P1o3s t}s} >>P o1s t?s  'qsu'i  :e n'g'a}g`e}n
                                                                                                                                                                                                                                          t .   G e n e r e s  <e/nb ustetcoonn>d
                                                                                                                                                                                                                                          e s . < / d i v ><
                                                                                                                                                                                                                                          / d i v > 
                                                                                                                                                                                                                                                < / d i v >{
                                                                                                                                                                                                                                                p o s t s . l<e/ndgitvh> 
                                                                                                                                                                                                                                                >   0   & &  <(d
                                                                                                                                                                                                                                                i v   s t y l e = { s<tdyilve>s
                                                                                                                                                                                                                                                . c o n t a i n e r } > 
                                                                                                                                                                                                                                                < h 2   s t y l e<=d{i{v  fsotnytlSei=z{es:t y1l8e,s .fcoanrtdW}e>i
                                                                                                                                                                                                                                                g h t :   7 0 0 ,   m<adrigvi ns:t y'l0e =0{ {1 6mpaxr'g i}n}B>o{tptoosmt:s .2l0e n}g}t>h
                                                                                                                                                                                                                                                }   p o s t { p o s t s .<lleanbgetlh  s>t y1l e?= {'sst'y l:e s'.'l}a bgeeln}e>rSeu{jpeots tdsu. lpeonsgtt h* <>/ l1a b?e l'>s
                                                                                                                                                                                                                                                '   :   ' ' } < / h 2 > 
                                                                                                                                                                                                                                                < t e x t a r e a   v a l{upeo=s{tssu.jmeatp}( (opnoCshta,n gie)= {=e>  =(>
                                                                                                                                                                                                                                                  s e t S u j e t ( e . t a r<gdeitv. vkaelyu=e{)i}}  psltaycleeh=o{lsdteyrl=e"sE.xp:o sCtoCmamredn}t> 
                                                                                                                                                                                                                                                  j   a i   m u l t i p l i e   m o<nd ievn gsatgyelmee=n{ts tLyilnekse.dpIons tpHaera d1e0r.}.>.
                                                                                                                                                                                                                                                  "   s t y l e = { s t y l e s . t e x<tsapraena }s tryolwes=={{{3 }f o/n>t
                                                                                                                                                                                                                                                  W e i g h t :   7 0 0<,/ dfiovn>t
                                                                                                                                                                                                                                                  S i z e :   1 3 ,   c<odliovr :s tBy l}e}=>{P{o smta r#g{iin B+o t1t}o<m/:s p2a0n >}
                                                                                                                                                                                                                                                  } > 
                                                                                                                                                                                                                                                                           < l a b<eblu tsttoynl eo=n{Csltiyclke=s{.(l)a b=e>l }c>oApuideirePnocset (cii,b lpeo s<ts)p}a ns tsytlyel=e{=s{t{y lfeosn.tcWoepiygBhttn:} >4{0c0o,p iceo l=o=r=:  iT L?,  'fCoonptiSei z!e':  :1 2' C}o}p>i(eorp't}i<o/nbnuetlt)o<n/>s
                                                                                                                                                                                                                                                                           p a n > < / l a b e l > 
                                                                                                                                                                                                                                                                                   < / d i v > 
                                                                                                                                                                                                                                                                                       < i n p u t   t y p e = " t e<xdti"v  vsatlyulee=={{asutdyileensc.ep}o sotnBCohdayn}g>e{=p{oes t=}>< /sdeitvA>u
                                                                                                                                                                                                                                                                                       d i e n c e ( e . t a r g e t . v<adliuve )s}t ypllea=c{e{h opladdedri=n"gE:x :' 8Epnxt r1e6pprxe'n,e ubrosr,d efrrTeoepl:a n'c1epsx,  smoalniadg e#rFs0.F.0.F"0 's,t yblaec=k{gsrtoyulnedsC.oilnopru:t }' #/F>A
                                                                                                                                                                                                                                                                                       F A F A '   } } > 
                                                                                                                                                                                                                                                                                         < / d i v > 
                                                                                                                                                                                                                                                                                                              <<dsipva ns tsytlyel=e{={{ {m afrognitnSBioztet:o m1:1 ,2 0c o}l}o>r
                                                                                                                                                                                                                                                                                                              :   T L   } } > ~ { p o s<tl.asbpelli ts(t'y l'e)=.{lsetnygltehs}. lmaobtesl<}/>sTpoanna>l
                                                                                                                                                                                                                                                                                                              i t e < / l a b e l > 
                                                                                                                                                                                                                                                                                                                        < / d i v > 
                                                                                                                                                                                                                                                                                                                          < d i v   s t y l e = { s t<y/ldeisv.>g
                                                                                                                                                                                                                                                                                                                          r i d } > 
                                                                                                                                                                                                                                                                                                                                        ) ) } 
                                                                                                                                                                                                                                                                                                                                                { T O N A L I<T/EdSi.vm>a
                                                                                                                                                                                                                                                                                                                                                p ( t   = >   ( 
                                                                                                                                                                                                                                                                                                                                                ) } 
                                                                                                                                                                                                                                                                                                                                                                 < d i v   s<tdyilve =k{esyt=y{lte.si.df}o ootneCrl}i>cPkr=o{p(u)l s=e>  psaert TColnaauldiet e·( tF.aiidt) }p osutry lLei=n{k{e d.I.n.<s/tdyilve>s
                                                                                                                                                                                                                                                                                                                                                                 . o p t i o n<C/adridv,> 
                                                                                                                                                                                                                                                                                                                                                                 . . . ( t<o/ndailvi>t
                                                                                                                                                                                                                                                                                                                                                                 e   =)=;=
                                                                                                                                                                                                                                                                                                                                                                  }t.id ? styles.optionCardActive : {}) }}>
                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 3 }}>{t.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: 11, color: TL }}>{t.desc}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label style={styles.label}>Type de hook</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={styles.hookGrid}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {HOOKS.map(h => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button key={h} onClick={() => setHook(h)} style={{ ...styles.hookBtn, ...(hook === h ? styles.hookBtnActive : {}) }}>{h}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label style={styles.label}>Nombre de posts : <strong>{nbPosts}</strong></label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="range" min={1} max={10} value={nbPosts} onChange={e => setNbPosts(Number(e.target.value))} style={{ width: '100%', accentColor: B }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {erreur && <p style={styles.erreur}>{erreur}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={genererPosts} disabled={loading} style={{ ...styles.btn, ...(loading ? styles.btnDisabled : {}) }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? 'Generation en cours...' : `Generer ${nbPosts} post${nbPosts > 1 ? 's' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {posts.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 16px' }}>{posts.length} post{posts.length > 1 ? 's' : ''} genere{posts.length > 1 ? 's' : ''}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {posts.map((post, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={i} style={styles.postCard}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={styles.postHeader}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ fontWeight: 700, fontSize: 13, color: B }}>Post #{i + 1}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => copierPost(i, post)} style={styles.copyBtn}>{copie === i ? 'Copie !' : 'Copier'}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={styles.postBody}>{post}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ padding: '8px 16px', borderTop: '1px solid #F0F0F0', backgroundColor: '#FAFAFA' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ fontSize: 11, color: TL }}>~{post.split(' ').length} mots</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={styles.footer}>Propulse par Claude · Fait pour LinkedIn</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
